cd ..
git clone https://github.com/game-simulations/worlds.git
git clone https://github.com/game-simulations/windows.git
git clone https://github.com/game-simulations/window-systems.git
git clone https://github.com/game-simulations/vulkan-renderer.git
git clone https://github.com/game-simulations/unmanaged.git
git clone https://github.com/game-simulations/ui-systems.git
git clone https://github.com/game-simulations/interaction-kit.git
git clone https://github.com/game-simulations/types.git
git clone https://github.com/game-simulations/transforms.git
git clone https://github.com/game-simulations/transform-systems.git
git clone https://github.com/game-simulations/textures.git
git clone https://github.com/game-simulations/texture-systems.git
git clone https://github.com/game-simulations/text-rendering-systems.git
git clone https://github.com/game-simulations/text-rendering.git
git clone https://github.com/game-simulations/skybox.git
git clone https://github.com/game-simulations/simulation
git clone https://github.com/game-simulations/shaders.git
git clone https://github.com/game-simulations/shader-systems.git
git clone https://github.com/game-simulations/serialization.git
git clone https://github.com/game-simulations/rendering-systems.git
git clone https://github.com/game-simulations/rendering.git
git clone https://github.com/game-simulations/physics-systems.git
git clone https://github.com/game-simulations/physics.git
git clone https://github.com/game-simulations/models.git
git clone https://github.com/game-simulations/model-systems.git
git clone https://github.com/game-simulations/meshes-9s
git clone https://github.com/game-simulations/meshes.git
git clone https://github.com/game-simulations/materials.git
git clone https://github.com/game-simulations/material-systems.git
git clone https://github.com/game-simulations/input-devices.git
git clone https://github.com/game-simulations/input-device-systems.git
git clone https://github.com/game-simulations/global-kbm-systems.git
git clone https://github.com/game-simulations/freetype.git
git clone https://github.com/game-simulations/fonts.git
git clone https://github.com/game-simulations/font-systems.git
git clone https://github.com/game-simulations/file-dialog.git
git clone https://github.com/game-simulations/expression-machine
git clone https://github.com/game-simulations/default-presentation-assets.git
git clone https://github.com/game-simulations/data-systems.git
git clone https://github.com/game-simulations/data.git
git clone https://github.com/game-simulations/collections.git
git clone https://github.com/game-simulations/clipboard.git
git clone https://github.com/game-simulations/cameras.git
git clone https://github.com/game-simulations/camera-systems.git
git clone https://github.com/game-simulations/bin-packer.git
git clone https://github.com/game-simulations/automations.git
git clone https://github.com/game-simulations/automation-systems.git
git clone https://github.com/game-simulations/abacus.git
