cd ..
git clone https://github.com/simulation-tree/xml.git
git clone https://github.com/simulation-tree/worlds.git
git clone https://github.com/simulation-tree/windows.git
git clone https://github.com/simulation-tree/window-systems.git
git clone https://github.com/simulation-tree/vulkan-renderer.git
git clone https://github.com/simulation-tree/unmanaged.git
git clone https://github.com/simulation-tree/ui.git
git clone https://github.com/simulation-tree/ui-systems.git
git clone https://github.com/simulation-tree/types.git
git clone https://github.com/simulation-tree/transforms.git
git clone https://github.com/simulation-tree/transform-systems.git
git clone https://github.com/simulation-tree/toml.git
git clone https://github.com/simulation-tree/textures.git
git clone https://github.com/simulation-tree/texture-systems.git
git clone https://github.com/simulation-tree/text-rendering.git
git clone https://github.com/simulation-tree/text-rendering-systems.git
git clone https://github.com/simulation-tree/skybox.git
git clone https://github.com/simulation-tree/simulation.git
git clone https://github.com/simulation-tree/shapes.git
git clone https://github.com/simulation-tree/shaders.git
git clone https://github.com/simulation-tree/shader-systems.git
git clone https://github.com/simulation-tree/rendering.git
git clone https://github.com/simulation-tree/rendering-systems.git
git clone https://github.com/simulation-tree/physics.git
git clone https://github.com/simulation-tree/physics-systems.git
git clone https://github.com/simulation-tree/particles.git
git clone https://github.com/simulation-tree/particle-systems.git
git clone https://github.com/simulation-tree/models.git
git clone https://github.com/simulation-tree/model-systems.git
git clone https://github.com/simulation-tree/meshes.git
git clone https://github.com/simulation-tree/meshes-9s.git
git clone https://github.com/simulation-tree/materials.git
git clone https://github.com/simulation-tree/material-systems.git
git clone https://github.com/simulation-tree/json.git
git clone https://github.com/simulation-tree/input-devices.git
git clone https://github.com/simulation-tree/input-device-systems.git
git clone https://github.com/simulation-tree/global-kbm-systems.git
git clone https://github.com/simulation-tree/freetype.git
git clone https://github.com/simulation-tree/fonts.git
git clone https://github.com/simulation-tree/font-systems.git
git clone https://github.com/simulation-tree/file-dialog.git
git clone https://github.com/simulation-tree/expression-machine.git
git clone https://github.com/simulation-tree/default-presentation-assets.git
git clone https://github.com/simulation-tree/data.git
git clone https://github.com/simulation-tree/data-systems.git
git clone https://github.com/simulation-tree/collections.git
git clone https://github.com/simulation-tree/clipboard.git
git clone https://github.com/simulation-tree/cameras.git
git clone https://github.com/simulation-tree/camera-systems.git
git clone https://github.com/simulation-tree/bin-packer.git
git clone https://github.com/simulation-tree/automations.git
git clone https://github.com/simulation-tree/automation-systems.git
