cd ..
git clone https://github.com/game-simulations/unmanaged.git
git clone https://github.com/game-simulations/simulation.git
git clone https://github.com/game-simulations/logging.git
git clone https://github.com/game-simulations/commander.git
git clone https://github.com/game-simulations/data.git
git clone https://github.com/game-simulations/meshes.git
git clone https://github.com/game-simulations/models.git
git clone https://github.com/game-simulations/shaders.git
git clone https://github.com/game-simulations/textures.git
git clone https://github.com/game-simulations/fonts.git
git clone https://github.com/game-simulations/transforms.git
git clone https://github.com/game-simulations/automations.git
git clone https://github.com/game-simulations/cameras.git
git clone https://github.com/game-simulations/serialization.git
git clone https://github.com/game-simulations/bin-packer.git
git clone https://github.com/game-simulations/rendering.git
git clone https://github.com/game-simulations/windows.git
git clone https://github.com/game-simulations/input-devices.git
git clone https://github.com/game-simulations/interaction-kit.git
git clone https://github.com/game-simulations/physics.git
git clone https://github.com/game-simulations/programs.git
git clone https://github.com/game-simulations/freetype.git
git clone https://github.com/game-simulations/default-presentation-assets.git
git clone https://github.com/game-simulations/expression-machine.git
git clone https://github.com/game-simulations/text-rendering.git
git clone https://github.com/game-simulations/http.git
git clone https://github.com/game-simulations/data-systems.git
git clone https://github.com/game-simulations/font-systems.git
git clone https://github.com/game-simulations/model-systems.git
git clone https://github.com/game-simulations/shader-systems.git
git clone https://github.com/game-simulations/texture-systems.git
git clone https://github.com/game-simulations/transform-systems.git
git clone https://github.com/game-simulations/window-systems.git
git clone https://github.com/game-simulations/physics-systems.git
git clone https://github.com/game-simulations/input-device-systems.git
git clone https://github.com/game-simulations/text-rendering-systems.git
git clone https://github.com/game-simulations/vulkan-renderer.git