name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `windows`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/windows
          token: ${{ secrets.PAT }}
          path: windows
      
      - name: Checkout `transforms`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Checkout `text-rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/text-rendering
          token: ${{ secrets.PAT }}
          path: text-rendering
      
      - name: Checkout `physics`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/physics
          token: ${{ secrets.PAT }}
          path: physics
      
      - name: Checkout `models`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/models
          token: ${{ secrets.PAT }}
          path: models
      
      - name: Checkout `ui`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/ui
          token: ${{ secrets.PAT }}
          path: ui
      
      - name: Checkout `input-devices`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/input-devices
          token: ${{ secrets.PAT }}
          path: input-devices
      
      - name: Checkout `default-presentation-assets`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/default-presentation-assets
          token: ${{ secrets.PAT }}
          path: default-presentation-assets
      
      - name: Checkout `data`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Checkout `cameras`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/cameras
          token: ${{ secrets.PAT }}
          path: cameras
      
      - name: Checkout `automations`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/automations
          token: ${{ secrets.PAT }}
          path: automations
      
      - name: Checkout `skybox`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/skybox
          token: ${{ secrets.PAT }}
          path: skybox
      
      - name: Checkout `meshes-9s`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/meshes-9s
          token: ${{ secrets.PAT }}
          path: meshes-9s
      
      - name: Checkout `file-dialog`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/file-dialog
          token: ${{ secrets.PAT }}
          path: file-dialog
      
      - name: Checkout `window-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/window-systems
          token: ${{ secrets.PAT }}
          path: window-systems
      
      - name: Checkout `vulkan-renderer`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/vulkan-renderer
          token: ${{ secrets.PAT }}
          path: vulkan-renderer
      
      - name: Checkout `transform-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transform-systems
          token: ${{ secrets.PAT }}
          path: transform-systems
      
      - name: Checkout `texture-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/texture-systems
          token: ${{ secrets.PAT }}
          path: texture-systems
      
      - name: Checkout `text-rendering-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/text-rendering-systems
          token: ${{ secrets.PAT }}
          path: text-rendering-systems
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `shader-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shader-systems
          token: ${{ secrets.PAT }}
          path: shader-systems
      
      - name: Checkout `physics-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/physics-systems
          token: ${{ secrets.PAT }}
          path: physics-systems
      
      - name: Checkout `model-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/model-systems
          token: ${{ secrets.PAT }}
          path: model-systems
      
      - name: Checkout `ui-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/ui-systems
          token: ${{ secrets.PAT }}
          path: ui-systems
      
      - name: Checkout `input-device-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/input-device-systems
          token: ${{ secrets.PAT }}
          path: input-device-systems
      
      - name: Checkout `font-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/font-systems
          token: ${{ secrets.PAT }}
          path: font-systems
      
      - name: Checkout `material-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/material-systems
          token: ${{ secrets.PAT }}
          path: material-systems
      
      - name: Checkout `global-kbm-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/global-kbm-systems
          token: ${{ secrets.PAT }}
          path: global-kbm-systems
      
      - name: Checkout `data-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/data-systems
          token: ${{ secrets.PAT }}
          path: data-systems
      
      - name: Checkout `camera-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/camera-systems
          token: ${{ secrets.PAT }}
          path: camera-systems
      
      - name: Checkout `automation-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/automation-systems
          token: ${{ secrets.PAT }}
          path: automation-systems
      
      - name: Checkout `rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/rendering
          token: ${{ secrets.PAT }}
          path: rendering
      
      - name: Checkout `shaders`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shaders
          token: ${{ secrets.PAT }}
          path: shaders
      
      - name: Checkout `meshes`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/meshes
          token: ${{ secrets.PAT }}
          path: meshes
      
      - name: Checkout `materials`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/materials
          token: ${{ secrets.PAT }}
          path: materials
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/collections
          token: ${{ secrets.PAT }}
          path: collections
      
      - name: Checkout `serialization`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/serialization
          token: ${{ secrets.PAT }}
          path: serialization
      
      - name: Checkout `freetype`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/freetype
          token: ${{ secrets.PAT }}
          path: freetype
      
      - name: Checkout `fonts`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/fonts
          token: ${{ secrets.PAT }}
          path: fonts
      
      - name: Checkout `clipboard`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/clipboard
          token: ${{ secrets.PAT }}
          path: clipboard
      
      - name: Checkout `textures`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/textures
          token: ${{ secrets.PAT }}
          path: textures
      
      - name: Checkout `bin-packer`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/bin-packer
          token: ${{ secrets.PAT }}
          path: bin-packer
      
      - name: Checkout `rendering-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/rendering-systems
          token: ${{ secrets.PAT }}
          path: rendering-systems
      
      - name: Checkout `shapes`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shapes
          token: ${{ secrets.PAT }}
          path: shapes
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `Abacus`
        run: dotnet build "${{ github.event.repository.name }}/program" -c Release /p:Version=${VERSION}
      
      - name: Build `Abacus.Simulator`
        run: dotnet build "${{ github.event.repository.name }}/simulator" -c Release /p:Version=${VERSION}
      
            
      - name: Pack `Abacus`
        run: dotnet pack "${{ github.event.repository.name }}/program" -c Release /p:Version=${VERSION} --no-build --output .
      
      - name: Pack `Abacus.Simulator`
        run: dotnet pack "${{ github.event.repository.name }}/simulator" -c Release /p:Version=${VERSION} --no-build --output .

      - name: Add NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `Abacus`
        run: dotnet nuget push Abacus.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      
      - name: Publish `Abacus.Simulator`
        run: dotnet nuget push Abacus.Simulator.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}